#!/usr/bin/python3

from argparse import ArgumentParser
from datetime import datetime, timedelta
from os import chdir, getcwd, makedirs, system, path
from shutil import rmtree
from socket import gethostname
from subprocess import call
from sys import exit
from time import localtime, strftime, strptime, time

arg = ArgumentParser()
#arg.add_argument('-s', help="Start Date")
#arg.add_argument('-e', help="End Date")
arg.add_argument('-d', help="Max Domains")
arg.add_argument('-t', help="Namelist Template Directory")
arg.add_argument('-H', help="Path to host list file")
arg.add_argument('-v', default=False, action='store_true', help="Run in verbose mode")
args = arg.parse_args()

NOW = datetime.now()-timedelta(days=1)
N_DAYS = 1

USERNAME='bnb32'

DIR_ROOT = '/data/'
DIR_OUT = DIR_ROOT + '%s/wrfout/' %(USERNAME)
DIR_LOG = DIR_OUT + 'logs/'
#DIR_LOCAL_TMP = DIR_ROOT + 'tmp/%s/' % NOW.strftime('%Y-%m-%d_%H-%M-%S')
#DIR_REMOTE_TMP = DIR_ROOT + 'local/wrf/tmp/%s/' % NOW.strftime('%Y-%m-%d_%H-%M-%S')
DIR_LOCAL_TMP = DIR_ROOT + 'tmp/%s/%s/' % (USERNAME,NOW.strftime('%Y-%m-%d'))
DIR_REMOTE_TMP = DIR_ROOT + 'local/wrf/tmp/%s/%s/' % (USERNAME,NOW.strftime('%Y-%m-%d'))
DIR_GFS = DIR_LOCAL_TMP + 'gfs/'
DIR_WPS = DIR_ROOT + 'WPS-4.2/'
DIR_WRF = DIR_ROOT + 'WRF-4.2/test/em_real/'
DIR_WPS_GEOG = DIR_ROOT + 'WPS_GEOG/'

if args.t != None:
    DIR_TEMPLATES = args.t + '/'
else:
    DIR_TEMPLATES = getcwd() + '/templates/'

CMD_LN = 'ln -sf %s %s'
CMD_CP = 'cp -r %s %s'
CMD_MV = 'mv %s %s'
CMD_CHMOD = 'sudo chmod -R %s %s'
CMD_LINK_GRIB = DIR_WPS + 'link_grib.csh ' + DIR_GFS + 'gfs.'

CMD_GEOGRID = DIR_WPS + 'geogrid.exe > '+DIR_LOG+'/geogrid.exe.log 2>&1'
CMD_UNGRIB = DIR_WPS + 'ungrib.exe > '+DIR_LOG+'/ungrib.exe.log 2>&1'
CMD_METGRID = DIR_WPS + 'metgrid.exe > '+DIR_LOG+'/metgrid.exe.log 2>&1'
CMD_REAL = DIR_WRF + 'real.exe > '+DIR_LOG+'/real.exe.log 2>&1'
CMD_WRF = 'time /usr/bin/mpiexec -f %s %swrf.exe > %s/wrf.exe.log 2>&1' % (DIR_TEMPLATES + 'hosts', DIR_WRF, DIR_LOG)

if args.v:
    CMD_GEOGRID = DIR_WPS + 'geogrid.exe'
    CMD_UNGRIB = DIR_WPS + 'ungrib.exe'
    CMD_METGRID = DIR_WPS + 'metgrid.exe'
    CMD_REAL = DIR_WRF + 'real.exe'
    CMD_WRF = 'time /usr/bin/mpiexec -f %s %swrf.exe' % (DIR_TEMPLATES + 'hosts', DIR_WRF)

HTTPS_PATH = 'https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.%s/'

if args.d != None and args.d > 0:
    MAX_DOMAINS = int(args.d)
else:
    MAX_DOMAINS = 1

try:
    with open(DIR_TEMPLATES + 'namelist.wps', 'r') as namelist:
        NAMELIST_WPS = namelist.read()
    with open(DIR_TEMPLATES + 'namelist.input', 'r') as namelist:
        NAMELIST_WRF = namelist.read()
except:
    print('Error reading namelist files')
    exit()

#try: rmtree(DIR_LOCAL_TMP)
#except: pass
makedirs(DIR_LOCAL_TMP,exist_ok=True)
#makedirs(DIR_REMOTE_TMP,exist_ok=True)
try: rmtree(DIR_LOG)
except: pass
makedirs(DIR_LOG,exist_ok=True)
makedirs(DIR_GFS,exist_ok=True)

chdir(DIR_LOCAL_TMP)

# WPS Links
cmd = CMD_LN % (DIR_WPS + 'geogrid', './')
cmd = cmd + '; ' + CMD_LN % (DIR_WPS + 'metgrid', './')
cmd = cmd + '; ' + CMD_LN % (DIR_WPS + 'ungrib/Variable_Tables/Vtable.GFS', 'Vtable')
system(cmd)

# WRF Links
cmd = CMD_LN % (DIR_WRF + '*.TBL', './')
cmd = cmd + '; ' + CMD_LN % (DIR_WRF + '*_DATA', './')
system(cmd)

# Insert Dates into Namelists
cur_hour = NOW.hour
if cur_hour >= 0 and cur_hour < 6: z = 0
elif cur_hour >= 6 and cur_hour < 12: z = 6
elif cur_hour >= 12 and cur_hour < 18: z = 12
else: z = 18
z = 18

#run_date = NOW.replace(hour = z,minute = 0,second = 0,microsecond = 0)
run_date = NOW.replace(hour = z, minute = 0, second = 0, microsecond = 0)
forecast_start = run_date.replace(day = run_date.day, hour = z)
forecast_end = forecast_start.replace(day = forecast_start.day + N_DAYS, hour = z)

# WPS Namelist
wps_dates = ' start_date = '
for i in range(0, MAX_DOMAINS):
    wps_dates = wps_dates + forecast_start.strftime("'%Y-%m-%d_%H:%M:%S', ")
wps_dates = wps_dates + '\n end_date = '
for i in range(0, MAX_DOMAINS):
    wps_dates = wps_dates + forecast_end.strftime("'%Y-%m-%d_%H:%M:%S', ")

with open('namelist.wps', 'w') as namelist:
    namelist.write(NAMELIST_WPS.replace('%DATES%', wps_dates))

# WRF Namelist

wrf_dates = ' run_days = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + '%s, ' %(N_DAYS)
wrf_dates = wrf_dates + '\n run_hours = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + '0, '
wrf_dates = wrf_dates + '\n run_minutes = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + '0, '
wrf_dates = wrf_dates + '\n run_seconds = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + '0, '
wrf_dates = wrf_dates + '\n start_year = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + forecast_start.strftime('%Y, ')
wrf_dates = wrf_dates + '\n start_month = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + forecast_start.strftime('%m, ')
wrf_dates = wrf_dates + '\n start_day = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + forecast_start.strftime('%d, ')
wrf_dates = wrf_dates + '\n start_hour = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + forecast_start.strftime('%H, ')
wrf_dates = wrf_dates + '\n start_minute = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + '00, '
wrf_dates = wrf_dates + '\n start_second = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + '00, '
wrf_dates = wrf_dates + '\n end_year = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + forecast_end.strftime('%Y, ')
wrf_dates = wrf_dates + '\n end_month = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + forecast_end.strftime('%m, ')
wrf_dates = wrf_dates + '\n end_day = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + forecast_end.strftime('%d, ')
wrf_dates = wrf_dates + '\n end_hour = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + forecast_end.strftime('%H, ')
wrf_dates = wrf_dates + '\n end_minute = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + '00, '
wrf_dates = wrf_dates + '\n end_second = '
for i in range(0, MAX_DOMAINS):
    wrf_dates = wrf_dates + '00, '

with open('namelist.input', 'w') as namelist:
    namelist.write(NAMELIST_WRF.replace('%DATES%', wrf_dates))

start_date = run_date.strftime('%Y%m%d%H')
local_gfs = DIR_GFS #+ 'gfs.' + start_date
remote_gfs = HTTPS_PATH % (run_date.strftime('%Y%m%d')+'/'+run_date.strftime('%H'))

makedirs(local_gfs,exist_ok=True)
startTime = int(time())

print("Downloading GFS data")

ftpQueue = []
for i in range(0, 24*N_DAYS+1, 3):
    hr = '%03d' % i
    #file_name = 'gfs.t%sz.pgrbf%s.grib2' % (start_date[-2:], hr)
    file_name = 'gfs.t%sz.pgrb2.1p00.f%s' % (start_date[-2:], hr)
    local_path = local_gfs + file_name
    remote_path = remote_gfs + file_name
    cmd='sudo wget -O '+local_path+' -q '+remote_path
    if not path.exists(local_path):
        system(cmd)

# Link the grib files
system(CMD_LINK_GRIB)

elapsed = int(time()) - startTime
print('GFS retrieved in: ' + str(elapsed))

startTime = int(time())
system(CMD_GEOGRID)

elapsed = int(time()) - startTime
print('Geogrid ran in: ' + str(elapsed))

startTime = int(time())
system(CMD_UNGRIB)

elapsed = int(time()) - startTime
print('Ungrib ran in: ' + str(elapsed))

startTime = int(time())
system(CMD_METGRID)

elapsed = int(time()) - startTime
print('Metgrid ran in: ' + str(elapsed))

startTime = int(time())
system(CMD_REAL)

elapsed = int(time()) - startTime
print('Real ran in: ' + str(elapsed))

cmd = CMD_CP % (DIR_LOCAL_TMP + 'rsl.*', DIR_LOG + 'real/')
makedirs(DIR_LOG + 'real/',exist_ok=True)
system(cmd)

#startTime = int(time())
#system(CMD_MV % (DIR_LOCAL_TMP, DIR_REMOTE_TMP))
#chdir(DIR_REMOTE_TMP)
#system(CMD_CHMOD % ('777', DIR_REMOTE_TMP))

#elapsed = int(time()) - startTime
#print('Files copied in: ' + str(elapsed))
startTime = int(time())
system(CMD_WRF)

elapsed = int(time()) - startTime
print('WRF ran in: ' + str(elapsed))

#cmd = CMD_CP % (DIR_REMOTE_TMP + 'wrfout*', DIR_OUT)
#cmd = cmd + '; ' + CMD_CP % (DIR_REMOTE_TMP + '*.log rsl.*', DIR_LOG)
#system(cmd)

cmd = CMD_CP % (DIR_LOCAL_TMP + 'rsl.*', DIR_LOG + 'wrf/')
makedirs(DIR_LOG + 'wrf/',exist_ok=True)
system(cmd)

cmd = CMD_CP % (DIR_LOCAL_TMP + 'wrfout*', DIR_OUT)
makedirs(DIR_OUT,exist_ok=True)
cmd = cmd + '; ' + CMD_CP % (DIR_LOCAL_TMP + '*.log rsl.*', DIR_LOG)
system(cmd)

#rmtree(DIR_REMOTE_TMP)
